config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root 'tasks#index'

  match '/tasks/complete/:id' => 'tasks#complete', as: 'complete_task', via: :put
  match '/tasks/complete/:id' => 'tasks#incomplete', as: 'incomplete_task', via: :delete

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :description
  scope :completed, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.completed = true
    @task.save
    redirect_to root_path
  end

  def incomplete 
    @task = Task.find(params[:id])
    @task.completed = false
    @task.save
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<div class="footer"> 
  <div class="container"> 
    <div class="row"> 
      <div class="col-md-12"> 
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Mon pense-bête</a>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Modifier la tâche</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>


<div>
  <div class="left_side">
    <h1>Tâches à réaliser</h1>
    <% if @tasks.incomplete.empty? %>
      <p>Qu'avez-vous à faire aujourd'hui ?</p>
    <% else %>
      <% @tasks.incomplete.each do |task| %>
        <p><%= link_to "Fait", complete_task_path(task), method: :put, :remote => true, class: "done_btn" %>
        <%= "| #{task.description} |  Créé le #{task.created_at.day}/#{task.created_at.month}" %>
        <%= link_to ' Modifier', edit_task_path(task), class: "hidden_choice" %>
        <%= link_to ' X', task, method: :delete, data: { confirm: 'Êtes-vous sur ?' }, class: "hidden_choice" %></p>
      <% end %>
    <% end %>
  </div>

  <div class="right_side">
    <h1>Tâches réalisées</h1><a href="#" id= "show_task"><p>Voir plus</p></a>
    <div id="hidden_task" class="hidden">
      <% @tasks.completed.each do |task| %>
      <p><%= link_to "A faire", incomplete_task_path(task), method: :delete, class: "done_btn" %><%= "| #{task.description} effectué le #{task.updated_at.day}/#{task.updated_at.month}" %>
      </p>
      <% end %>
    </div>
  </div>

  <div>
    <%= form_for @task, :remote => true  do |f| %>
      <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :description, placeholder: 'Nouvelle tâche' %>
      </div>
      <div class="actions">
        <%= f.submit "Ajouter", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

</div>

<script> 
  $(function() {
    $('a#show_task').click(function(event){
      event.preventDefault();
      $('div#hidden_task').toggle();
    });
  });  
</script>

app/views/tasks/new.html.erb
<h2>Nouvelle tâche</h2>

<%= render 'form' %>

<%= link_to 'Retour', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Modifier', edit_task_path(@task) %> |
<%= link_to 'Supprimer', tasks_path %>